<!DOCTYPE breakfast_menu [
        <!ELEMENT breakfast_menu (food|x-path)*>
        <!ELEMENT food (name|price|description|calories)*>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT calories (#PCDATA)>
        <!ELEMENT x-path (add)*>
        <!ELEMENT add (#PCDATA)>
        <!ATTLIST add
                key CDATA #REQUIRED
                value CDATA #REQUIRED>
        ]>
<breakfast_menu>
    <food>
        <name>Belgian Waffles</name>
        <price>$5.95</price>
        <description>Two of our famous Belgian Waffles with plenty of real maple syrup</description>
        <calories>650</calories>
    </food>
    <food>
        <name>asda Belgian Waffles</name>
        <price>$7.95</price>
        <description>Light Belgian waffles covered with strawberries and whipped cream</description>
        <calories>900</calories>
    </food>
    <food>
        <name>Berry-Berry Belgian Waffles</name>
        <price>$8.95</price>
        <description>Light Belgian waffles covered with an assortment of fresh berries and whipped cream</description>
        <calories>900</calories>
    </food>
    <food>
        <name>French Toast</name>
        <price>$4.50</price>
        <description>Thick slices made from our homemade sourdough bread</description>
        <calories>600</calories>
    </food>
    <food>
        <name>Homestyle Breakfast</name>
        <price>$6.95</price>
        <description>Two eggs, bacon or sausage, toast, and our ever-popular hash browns</description>
        <calories>950</calories>
    </food>
    <x-path>
        <add key="el_FullQueryConduct_XPath" value="//label[@for='QueryType-Full']"/>
        <add key="el_FullQPreEmpRadio_XPath" value="//label[@for='PreEmployment-True']"/>
        <add key="el_LimitedQryConsent_XPath" value="//label[@for='ConsentObtained']"/>
        <add key="el_SubmitQuery_ElementId" value="OtherButton"/>
        <add key="el_QuerySubmitted_ClassName" value="success-box"/>
    </x-path>
</breakfast_menu>


